scouting_hub:
  db:
    url: jdbc:mysql://localhost:13306/scoutinghub
    username: root
    password: root

spring:
  application:
    name: scouting-hub
  datasource:
    url: ${scouting_hub.db.url}
    username: ${scouting_hub.db.username}
    password: ${scouting_hub.db.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  liquibase:
    change-log: classpath:/config/liquibase/master.xml
    enabled: true
  jpa:
    properties:
      hibernate:
        type:
          wrapper_array_handling: ALLOW
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
